Support directives on type definition fields
alumbra/alumbra.parser pull request #6
Opened 2018-04-30 21:23 UTC by kipz

- Also add support for using | to separate directive locations
- Change .travis.yml to use `lein` instead of `lein2` (which is the default now, and whose symlink is broken)

The build does not fail for me locally (modern linux, lein 2.8.1, openjdk 1.8.0_162 or Oracle JDK 1.8.1_171), so I'm really not sure why it's breaking on travis.

I think this is consistent with the draft spec: http://facebook.github.io/graphql/draft/#sec-Type-System.Directives

2018-05-01 16:34 UTC, xsc requested changes

2018-05-01 16:34 UTC, xsc commented on resources/alumbra/GraphQLSchema.g4
> +    : directiveLocation ( '|'? directiveLocation )*
If I understand the [GraphQL grammar](http://facebook.github.io/graphql/draft/#DirectiveLocations) correctly here, this form should be:

```
'|'? directiveLocation ( '|' directiveLocation )*
```

I.e. the first `|` is optional but the others are not.

2018-05-01 16:34 UTC, xsc commented on test/alumbra/parser/schema_test.clj
> +                     directive @example on FIELD_DEFINITION | ARGUMENT_DEFINITION
There is already a test for the `directive` definition a few testcases above, so you can remove it here.

2018-05-01 16:34 UTC, xsc commented
Looking good! Thanks for picking this up!

2018-05-01 17:11 UTC, kipz commented on resources/alumbra/GraphQLSchema.g4
> +    : directiveLocation ( '|'? directiveLocation )*
@xsc yeah, but I think that would be a breaking change for alumbra because previously these were not required (and commas are allowed). I'm happy either way though. What do you think?

2018-05-02 08:42 UTC, xsc commented on resources/alumbra/GraphQLSchema.g4
> +    : directiveLocation ( '|'? directiveLocation )*
The other changes (moving directives around) are already breaking, so that's okay.

2018-05-03 12:11 UTC, kipz commented
@xsc I've made the changes requested. Thanks for looking at this PR and for maintaining this project! :)

2018-05-11 10:22 UTC, xsc approved these changes

2018-05-11 10:22 UTC, merged